define({
  root: {
    mapLayerTitle: "Layers",
    baseMapTopoRDVTitle: "Topo",
    baseMapAerialPhotoTitle: "AerialPhoto",
    watertappuntenFeatureLayerTitle: "Watertaps",
    horecaFeatureLayerTitle: "Hotels, restaurants and cafés with tabwater",
    errorMessageLocationNotProvided: "Location not provided",
    errorMessageLocationNotAvailable: "Current location not available",
    errorMessageLocationTimeout: "Timeout retreiving the location",
    errorMessageUnknownError: "Unknown error",
    messageProjectionNotSupported: "Projection is not supported"    
  },
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "el": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 1,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0
});
